/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author gsv
 */
public class Cronometro extends javax.swing.JFrame {

    /**
     * Creates new form Cronometro
     */
    public Cronometro() {
        initComponents();
        setLocationRelativeTo(null);
        timer = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPausar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblms = new javax.swing.JLabel();
        lblh = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lbls = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(91, 37, 37));
        jPanel1.setForeground(new java.awt.Color(71, 75, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPausar.setBackground(new java.awt.Color(153, 153, 153));
        btnPausar.setText("Pausar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 99, -1));

        btnParar.setBackground(new java.awt.Color(153, 153, 153));
        btnParar.setText("Detener");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        jPanel1.add(btnParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 99, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("M");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 20, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 210, 10));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("H");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 20, 20));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("S");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 20, 20));

        lblms.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblms.setForeground(new java.awt.Color(0, 255, 102));
        lblms.setText("00");
        jPanel1.add(lblms, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 40));

        lblh.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblh.setForeground(new java.awt.Color(0, 255, 102));
        lblh.setText("00:");
        jPanel1.add(lblh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 40));

        lblm.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblm.setForeground(new java.awt.Color(0, 255, 102));
        lblm.setText("00:");
        jPanel1.add(lblm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, 40));

        lbls.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbls.setForeground(new java.awt.Color(0, 255, 102));
        lbls.setText("00:");
        jPanel1.add(lbls, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 60, 40));

        jPanel2.setBackground(new java.awt.Color(108, 101, 113));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbltitulo.setText("Cronómetro");
        jPanel2.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("MS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 30, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 230, 120));

        btnIniciar.setBackground(new java.awt.Color(153, 153, 153));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 99, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Todo el codigo principal esta aqui!!! darle en el boton en la cajita con
     * el icono de +
     */
    // <editor-fold defaultstate="collapsed" desc="Codigo Principal">                          
    private final Timer timer;  // Variable timer
    private int h, m, s, ms;    // variables de hora, minuto, segundo, milisegundo

    private final ActionListener acciones = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            ms++;
            // Milisegundos
            if (ms == 100) {
                ms = 0;
                s++;
                // Segundos
                if (s == 60) {
                    s = 0;
                    m++;
                    // Minutos        
                    if (m == 60) {
                        m = 0;
                        h++;
                    }
                }
            }
            actualizar();
        }
    };

    // Inicio actualizar
    private void actualizar() {

        if (h <= 9) {
            lblh.setText("0" + h + ":");
        } else {
            lblh.setText("" + h + ":");
        }
        if (m <= 9) {
            lblm.setText("0" + m + ":");
        } else {
            lblm.setText("" + m + ":");
        }
        if (s <= 9) {
            lbls.setText("0" + s + ":");
        } else {
            lbls.setText("" + s + ":");
        }
        if (ms <= 9) {
            lblms.setText("0" + ms);
        } else {
            lblms.setText("" + ms);
        }
    } // Fin actualizar

    // Inicio ctrlIniciar
    private void ctrlIniciar() {
        btnPausar.setEnabled(true);
        btnParar.setEnabled(true);
        btnIniciar.setEnabled(false);
        btnIniciar.setText("Reanudar");

    } // Fin ctrlIniciar

    // Inicio ctrlPausar
    private void ctrlPuasar() {
        btnIniciar.setEnabled(true);
        btnPausar.setEnabled(false);

    }// Fin ctrlPausar

    // Iniciar ctrlParar
    private void ctrlDetener() {
        btnIniciar.setEnabled(true);
        btnIniciar.setText("Iniciar");
        btnPausar.setEnabled(false);
        btnParar.setEnabled(false);
    }// Fin ctrlParar

    // Inicio reset
    private void reset() {
        ms = s = m = h = 0;
        actualizar();
    } // </editor-fold> 


    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        timer.start();
        ctrlIniciar();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        timer.stop();
        ctrlPuasar();
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        if (timer.isRunning()) {
            timer.stop();
        }
        ctrlDetener();
        reset();
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblh;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lblms;
    private javax.swing.JLabel lbls;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
